---
- name: Apply TCP Tweaks
  hosts: all
  become: true
  tasks:
    - name: Increase Core receive buffer size (net.core.rmem_max)
      ansible.posix.sysctl:
        name: net.core.rmem_max
        value: "134217728"
        state: present
        reload: true

    - name: Increase Core send buffer size (net.core.wmem_max)
      ansible.posix.sysctl:
        name: net.core.wmem_max
        value: "134217728"
        state: present
        reload: true

    - name: Increase TCP receive buffer (net.ipv4.tcp_rmem)
      ansible.posix.sysctl:
        name: net.ipv4.tcp_rmem
        value: "16384 262144 134217728"
        state: present
        reload: true

    - name: Increase TCP send buffer (net.ipv4.tcp_wmem)
      ansible.posix.sysctl:
        name: net.ipv4.tcp_wmem
        value: "16384 262144 134217728"
        state: present
        reload: true
