---
- name: Generate Server Inventory Report
  hosts: all, localhost
  gather_facts: true
  tasks:
    - name: Initialize CSV report  # noqa: run-once[task]
      ansible.builtin.copy:
        content: "Host,OS,Virtualization,Architecture,Cores,RAM_GB,Disk_GB,Uptime_Days\n"
        dest: /tmp/server_inventory.csv
        mode: '0644'
      delegate_to: localhost
      run_once: true

    - name: Calculate disk size
      ansible.builtin.set_fact:
        disk_size: 0

    - name: Sum physical disks
      ansible.builtin.set_fact:
        disk_size: "{{ disk_size | float + ((item.value.sectors | default(0) | int) * (item.value.sectorsize | default(0) | int) / (1024**3)) }}"
      loop: "{{ ansible_devices | default({}) | dict2items }}"
      when:
        - item.key is match('^(sd|vd|nvme|hd)[a-z]+$')
        - item.value.sectors is defined
        - item.value.sectorsize is defined

    - name: Write to CSV
      ansible.builtin.lineinfile:
        path: /tmp/server_inventory.csv
        line: "{{ inventory_hostname }},{{ ansible_distribution }} {{ ansible_distribution_version }},\
               {{ ansible_virtualization_type | default('physical') }},{{ ansible_architecture }},\
               {{ ansible_processor_vcpus }},{{ (ansible_memtotal_mb / 1024) | round(2) }},\
               {{ disk_size | round(1) }},{{ (ansible_uptime_seconds / 86400) | int }}"
        create: true
        mode: '0644'
      delegate_to: localhost
      run_once: false
      throttle: 1
