- hosts: all
  become: true
  gather_facts: yes
  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest
    - name: Install packages
      apt: "name={{ item }} state=latest update_cache=yes"
      loop:
        - apt-transport-https
        - btop
        - ca-certificates
        - curl
        - ccze
        - dnsutils
        - git
        - iftop
        - iperf3
        - jq
        - mtr-tiny
        - nano
        - neofetch
        - net-tools
        - nmap
        - python3
        - python3-pip
        - python3-setuptools
        - screen
        - shellcheck
        - software-properties-common
        - tar
        - tmux
        - traceroute
        - tree
        - unzip
        - vim
        - virtualenv
        - vnstat
        - wget
        - xz-utils
        - zip
    - name: Install pip packages
      ansible.builtin.pip:
        name:
          - jc
