---
- name: Configure User and SSH
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Add User ({{ user | default('jungle') }})
      ansible.builtin.user:
        name: "{{ user | default('jungle') }}"
        shell: /usr/bin/bash
        groups: sudo

    - name: Add User to the sudoers ({{ user | default('jungle') }})
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/{{ user | default('jungle') }}"
        content: "{{ user | default('jungle') }} ALL=(ALL) NOPASSWD: ALL"
        mode: "0440"

    - name: Add SSH Public Key for User ({{ user | default('jungle') }})
      ansible.posix.authorized_key:
        user: "{{ user | default('jungle') }}"
        state: present
        key: https://keys.devjugal.com/ssh

    - name: Disable Password Authentication
      ansible.builtin.lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication no"
        state: present
        backup: true

    - name: Disable Root Login
      ansible.builtin.lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"
        state: present
        backup: true

    - name: Restart SSH Service
      ansible.builtin.service:
        name: ssh
        state: restarted
