---
- name: Clean up unused Docker resources
  hosts: Server01, Server03, Server04, Server05, Server06, Server07
  become: true
  tasks:
    - name: Run docker system prune
      ansible.builtin.shell: docker system prune -f
      register: prune_result

    - name: Display the result of docker system prune
      ansible.builtin.debug:
        var: prune_result.stdout_lines
