---
- name: Deploy Systemd Timer for Docker Prune
  hosts: all
  become: true
  tasks:
    - name: Ensure Docker prune service unit file is present
      ansible.builtin.copy:
        dest: /etc/systemd/system/docker-prune.service
        mode: "0644"
        content: |
          [Unit]
          Description=Prune unused Docker objects

          [Service]
          Type=oneshot
          ExecStart=/usr/bin/docker system prune --all --force --volumes

      notify: Reload systemd

    - name: Ensure Docker prune timer unit file is present
      ansible.builtin.copy:
        dest: /etc/systemd/system/docker-prune.timer
        mode: "0644"
        content: |
          [Unit]
          Description=Weekly Docker system prune

          [Timer]
          OnCalendar=daily
          Persistent=true

          [Install]
          WantedBy=timers.target

      notify: Reload systemd

    - name: Enable and start the Docker prune timer
      ansible.builtin.systemd:
        name: docker-prune.timer
        enabled: true
        state: started

  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true
      become: true
