---
- name: Clean up unused Docker resources
  hosts: Server01, Server02, Server03
  become: yes
  tasks:
    - name: Run docker system prune
      shell: docker system prune -f
      register: prune_result

    - name: Display the result of docker system prune
      debug:
        var: prune_result.stdout_lines
