---
- name: Upgrade Cloudflared
  hosts: Server01, Server03, Server05, Server06
  become: yes

  vars:
    deb_urls:
      amd64: "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb"
      arm64: "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm64.deb"

    service_names:
      Server01: "cloudflared.service"
      Server03: "cloudflared.service"
      Server05: "cloudflared.service"
      Server06: "cloudflared.service"

  tasks:
    - name: Get Installed Version
      shell: cloudflared --version
      register: cloudflared_version

    - name: Print Installed Version
      debug:
        msg: "Installed Cloudflared version: {{ cloudflared_version.stdout }}"

    - name: Check Architecture
      command: dpkg --print-architecture
      register: dpkg_architecture
      changed_when: false

    - name: Print Architecture
      debug:
        msg: "Detected architecture: {{ dpkg_architecture.stdout }}"

    - name: Set Architecture Specific URL
      set_fact:
        deb_url: "{{ deb_urls[dpkg_architecture.stdout] }}"

    - name: Download Cloudflared .deb Package
      get_url:
        url: "{{ deb_url }}"
        dest: "/tmp/cloudflared.deb"

    - name: Upgrade Cloudflared
      apt:
        deb: "/tmp/cloudflared.deb"
        state: present
      register: cloudflared_upgrade_result

    - name: Restart Cloudflared Service
      systemd:
        name: "{{ service_names[inventory_hostname] }}"
        state: restarted
      when: cloudflared_upgrade_result.changed == true
