---
- name: Install Nginx from official nginx.org repos on Debian/Ubuntu
  hosts: all
  become: true
  vars:
    nginx_fingerprint: "573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62"
  tasks:
    - name: Gather facts
      ansible.builtin.setup:

    - name: Install prerequisites (Debian)
      ansible.builtin.apt:
        name:
          - curl
          - gnupg2
          - ca-certificates
          - lsb-release
          - debian-archive-keyring
        state: present
        update_cache: true
      when: ansible_facts['os_family'] == "Debian" and ansible_facts['distribution'] == "Debian"

    - name: Install prerequisites (Ubuntu)
      ansible.builtin.apt:
        name:
          - curl
          - gnupg2
          - ca-certificates
          - lsb-release
          - ubuntu-keyring
        state: present
        update_cache: true
      when: ansible_facts['os_family'] == "Debian" and ansible_facts['distribution'] == "Ubuntu"

    - name: Download nginx signing key
      ansible.builtin.get_url:
        url: https://nginx.org/keys/nginx_signing.key
        dest: /tmp/nginx_signing.key
        mode: "0644"

    - name: Import nginx signing key
      ansible.builtin.command: gpg --dearmor -o /usr/share/keyrings/nginx-archive-keyring.gpg /tmp/nginx_signing.key
      args:
        creates: /usr/share/keyrings/nginx-archive-keyring.gpg

    - name: Add nginx.org APT repository (Debian)
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/debian {{ ansible_lsb.codename }} nginx"
        filename: nginx
        state: present
      when: ansible_facts['os_family'] == "Debian" and ansible_facts['distribution'] == "Debian"

    - name: Add nginx.org APT repository (Ubuntu)
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/ubuntu {{ ansible_lsb.codename }} nginx"
        filename: nginx
        state: present
      when: ansible_facts['os_family'] == "Debian" and ansible_facts['distribution'] == "Ubuntu"

    - name: Set APT pinning to prefer nginx.org packages
      ansible.builtin.copy:
        dest: /etc/apt/preferences.d/99nginx
        content: |
          Package: *
          Pin: origin nginx.org
          Pin: release o=nginx
          Pin-Priority: 900
        mode: "0644"

    - name: Update apt cache after adding nginx repo
      ansible.builtin.apt:
        update_cache: true

    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Ensure nginx is started and enabled
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: true
