---
- name: Install Caddy Server from official Cloudsmith repo on Debian/Ubuntu
  hosts: all
  become: true
  tasks:
      - name: Install prerequisites
        ansible.builtin.apt:
            name:
                - debian-keyring
                - debian-archive-keyring
                - apt-transport-https
                - curl
            state: present
            update_cache: true

      - name: Download Caddy GPG key
        ansible.builtin.get_url:
            url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
            dest: /tmp/caddy-stable-archive-keyring.gpg
            mode: "0644"

      - name: Add Caddy GPG key
        ansible.builtin.command: gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg /tmp/caddy-stable-archive-keyring.gpg
        args:
            creates: /usr/share/keyrings/caddy-stable-archive-keyring.gpg

      - name: Add Caddy apt repository
        ansible.builtin.get_url:
            url: https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt
            dest: /etc/apt/sources.list.d/caddy-stable.list
            mode: "0644"

      - name: Update apt cache
        ansible.builtin.apt:
            update_cache: true

      - name: Install Caddy
        ansible.builtin.apt:
            name: caddy
            state: present

      - name: Ensure Caddy service is started and enabled
        ansible.builtin.systemd:
            name: caddy
            state: started
            enabled: true
