---
- name: Setup vnStat and Cron Job
  hosts: all
  become: true
  tasks:
    - name: Remove legacy vnstat cron job
      ansible.builtin.shell: |
        set -o pipefail
        (crontab -l 2>/dev/null || true) | grep -v "vnstat.*> /usr/share/caddy/stats" | crontab -
      args:
        executable: /bin/bash
      changed_when: false

    - name: Ensure vnstat is installed
      ansible.builtin.package:
        name: vnstat
        state: present

    - name: Ensure Caddy web root exists
      ansible.builtin.file:
        path: /usr/share/caddy
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Update vnstat stats cron job
      ansible.builtin.cron:
        name: "Update vnstat stats"
        minute: "*"
        job: "vnstat --iface {{ ansible_facts['default_ipv4']['interface'] | default('eth0') }} > /usr/share/caddy/stats"
        state: present
