---
- name: Install Smartctl Exporter
  hosts: PVE, PVE01, PVE02
  become: true

  pre_tasks:
    - name: Ensure smartmontools is installed
      ansible.builtin.package:
        name: smartmontools
        state: present

  roles:
    - role: prometheus.prometheus.smartctl_exporter
      vars:
        smartctl_exporter_version: "latest"
        smartctl_exporter_web_listen_address: "0.0.0.0:9633"
        smartctl_exporter_system_user: "root"
        smartctl_exporter_system_group: "root"
        smartctl_exporter_smartctl_interval: "60s"
        smartctl_exporter_smartctl_rescan: "10m"
        smartctl_exporter_smartctl_devices: "{{ smartctl_devices | default([]) }}"
