- name: Upgrade all apt packages to latest
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
      register: apt_upgrade_output

    - name: Print Upgraded Packages
      ansible.builtin.debug:
        var: apt_upgrade_output.stdout_lines
